require:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake

# trying to be good  O:)
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    # '___' prefixed dirs are excluded
    - ___*/**/*
    # avoid Error: RuboCop found unsupported Ruby version 2.1 in `TargetRubyVersion` parameter
    # (in vendor/bundle/ruby/3.0.0/gems/rainbow-3.0.0/.rubocop.yml) and also the extra weird
    # "Unable to find gem panolint; is the gem installed? Gem::MissingSpecError" in all ruby versions
    - vendor/bundle/**/*
    - pnpm/**/*

Layout/LineLength:
  Max: 130
  Exclude:
  - test/**/*

Layout/ExtraSpacing:
  AllowForAlignment:
    Enabled: true
  AllowBeforeTrailingComments:
    Enabled: true
  Exclude:
    - test/**/*

Layout/EmptyLines:
  Exclude:
    - lib/config/pagy.rb

Layout/BlockAlignment:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword

Layout/HashAlignment:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

# bad for performance
Metrics:
  Enabled: false

Naming/VariableNumber:
  CheckSymbols: false

Naming/MethodParameterName:
  Enabled: false

# not cool
Style/CommentedKeyword:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/LambdaCall:
  Enabled: false


# cannot inline the disabling in the file because rubocop complains anyway
Style/RedundantInitialize:
  Exclude:
    - test/mock_helpers/arel.rb

# Please!
Style/StringConcatenation:
  Enabled: false

# these cops are disabled only in the test files in order to
# allow to copy and paste the failed output for test reconciliation
Style/StringLiterals:
  Enabled: true
  Exclude:
  - test/**/*

Style/HashSyntax:
  Enabled: true
  Exclude:
    - test/**/*

Layout/SpaceAroundOperators:
  Enabled: true
  Exclude:
    - test/**/*

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  Exclude:
    - test/**/*

# rubocop bug already fixed in https://github.com/rubocop/rubocop/pull/11754 but not yet in the gem
Style/RedundantLineContinuation:
  Enabled: false
